name: Run Release Please

on:
  push:
    branches:
      - main

env:
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.19
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_PAGES_BRANCH: gh-pages

permissions:
  contents: read

jobs:
  build-oci:
    permissions:
      packages: write # to push the container image 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  

      - name: Log in to the Container registry
        uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          
  release-assets:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
 
        - name: Setup go
          uses: actions/setup-go@v3
          with:
            go-version: ${{ env.DEFAULT_GO_VERSION }}
        - run: |
            make release-manifests
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: latest
            files: |
              config/rendered/release.yaml
